serial:
    port: /dev/cu.usbserial-110
    baud: 115200
mappings:
    - knob: 1
      target: master_out
      step: 0.02
      sensitivity: normal
    - knob: 2
      target: mic_in
      step: 0.02
      sensitivity: normal
    - knob: 3
      target: master_out
      step: 0.02
      sensitivity: normal
    - knob: 4
      target: master_out
      step: 0.02
      sensitivity: normal
    - knob: 5
      target: master_out
      step: 0.02
      sensitivity: normal
default_template: universal
debug: false
